
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1EVXhOVEV5TWpjd09Wb1hEVE16TURVeE1qRXlNamN3T1Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBT0loCjRVVGQ4QlhKS1dKY1lFSXRCR3NjRHYwOXVCdUI0Q1hkQjFOL0EzcDdpRHhzNG9FL25zS085eGNxSzJNcFFZbmQKVlBDM3BrcFVwRUZ5U1BJUGM5OWtGN3F3YmFQbnNBUVU3b2I5WEw4THAvbUUrUHVhWElGWXJKYVdtMXVwT1hWeAplWnBrSGpzVGF6QXpBSlNiNUdKTnBlU2lTRnZIWEpKdXFlUnNPenkwa2RtbnFtNlVObDhrWUM4eTg1TE02WnRtCjhvaHFBeUpOR0Y1NFR5MW1PVjU5VmJuOFRDa0V4bDdkZW1YN3hyYmJDckc1eHRVRTByT0k2c08xTVZWc3FYWFMKR3lJT3ZEcXY0UWJTUlRGbkNYR1ZZSE1uTTBMQ2hUK0prbEVhbWRLNTU2bUY2VXhXZzRvQ1JuZy8yOXQ5djFNTAo5Z2dES2VwL0NBVm9BQjd3NGRrQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZJd2hZZnZmcDA4cE9lOXVxY2lXMzMva0JCN1RNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQjJwOFhycDdUallGQnNpdDBDZQppWUFudGFDREFNOVF6Qm9BcW40TjhiZGpyZXZOVkcvU002bjNjKzVRK0V4cDlRS2s4OW5idzhCeS8wdm5YRmJ2Cm1iMEdCVGJFeXdUYms0cEZ5dlZuRVI0dEFqOEIyQ2RXbDliOXg1b2RPL3B2ZmdpYlY0dERtdWkrVWRDN1cvMnUKeVlMSnlKRWdaMXIvZFNyYnE1TU45Tmk2RjljUlkxRjRqQmRaVXhIbDBqVlFvQjB2b0tVQ0d5bnhCTHo3UC9pdAo4cUxBZCtaZS9HRFllUkdFMElKNmJ4Q0JqVGRCOVpuVThyUlkxV3d1WTR5MTlNd3MyYVhVRFh5R3hHM0plV1d5CkFEQk5QU2ZMdGk2bGxUY2d4N3EwdmxIMFo3aWxqVkQ0a2NWbHd3SmMxZHVlQzFsNHI1aFZnUEs2VzZqekFqeEYKRkdvPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://229086c0-0ab9-44a1-b294-625cbe2b509d.us-southeast-1.linodelke.net:443
  name: lke108253

users:
- name: lke108253-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjF2cGNCMVJPX0xUZWo2TEJFQXVrZHdkazhMU044MmJxOFY5TmhQQ21BWEEifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tcGM0OWciLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiOGM1NTAxMDktYjU5Ni00MTI1LWE3NzgtZTVhZDRiMjYwYWFjIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.CUw5tLMiYcSofIXKHV4KMMLU5yiNsHC8t3jyFwE0W6eDu1e4tRKujEQHDB8AcBVAGmFMRxdVzxbpXfphvI0xWC9Wg7dbpObUzuWaapWUJbIWQAg2nw7dvTKX7eSY6iBSutvxNvQmDPdG32GQ5G43-vowC4KKT60aGo4UR1zbXKyPDINkbAy9uDjHIRuzvy20GNnjezP1dUFjOk8xicnum8Jcv3BZ_IpbpSErnZSvc_1PD1V83k7056CEmK9fhDiFpnDChXpiYwkyDj6Kb-uSUUfZ1wGRvDZrJPv3AwygtlhCfezvYeiglje_DJlJ7zZRM6NAKfVeSn5jIg1s-iWuyQ

contexts:
- context:
    cluster: lke108253
    namespace: default
    user: lke108253-admin
  name: lke108253-ctx

current-context: lke108253-ctx
