---
- name: Kubernetes
  hosts: localhost
  tasks:
    - name: Create a k8s namespace
      vars:
        ansible_python_interpreter: /usr/bin/python3
      kubernetes.core.k8s:
        name: my-app
        api_version: v1
        kind: Namespace
        state: present
        kubeconfig: /home/mubarak/Ansible/ansible-kubeconfig.yaml
    - name: Deploy nginx
      kubernetes.core.k8s:
        src: /home/mubarak/Ansible/nginx.yaml
        namespace: my-app
        state: present
